### ISSUE TITLE
Broken link for HPO guide 

### ISSUE THREAD

**Issue by eliorc** [allegroai/clearml-docs#21]
In the [Hyperparameter Optimization](https://clear.ml/docs/latest/docs/fundamentals/hpo#clearmls-hyperparameter-optimization) docs there is a broken link to the tutorial. 
At the bottom of the page there is this linke

_Check out the [Hyperparameter Optimization](https://clear.ml/docs/latest/docs/guides/optimization/hyper-parameter-optimization) tutorial for a step by step guide._ which links to a non existent page

**Comment by ainoam** [comment]
Thanks for the spot @eliorc. Should be fixed soon.

**Comment by ainoam** [comment]
@eliorc Docs updated. Thanks again.
