### ISSUE TITLE
task.upload_artifact() example does not work

### ISSUE THREAD

**Issue by AjeelAhmed1998** [allegroai/clearml-docs#343]
Link to the exact section: [here](https://github.com/allegroai/clearml-docs/blob/1a46cbdb932795a417d63706398947b6f44eb996/docs/getting_started/ds/ds_second_steps.md#adding-artifacts)

`task.upload_artifact('/path/to/preprocess_data.csv', name='data')`

The above code will not work because the first positional argument and the keyword argument `name` both are trying to fill in the `name` variable in the function. You can see the function in the codebase [here](https://github.com/allegroai/clearml/blob/1eee271f01a141e41542296ef4649eeead2e7284/clearml/binding/artifacts.py#L350).

**Comment by AjeelAhmed1998** [comment]
I can not tell by the codebase which argument is supposed to be used as `name`. If someone can let me know I'll create a PR.

**Comment by shomratalon** [comment]
Hi @AjeelAhmed1998 ,

I think you are right, the usage should be as in https://github.com/allegroai/clearml/blob/master/examples/reporting/artifacts.py#L39 - 

```
task.upload_artifact(name='Numpy Eye', artifact_object=np.eye(100, 100))
```

**Comment by ainoam** [comment]
Thanks for noticing @AjeelAhmed1998. Fixed in https://github.com/allegroai/clearml-docs/pull/351
