### ISSUE TITLE
Improve layout of docstrings in web documentation

### ISSUE THREAD

**Issue by Make42** [allegroai/clearml-docs#486]
I made a pull request to improve the docstrings for mark_completed and close, but now the web documentations

- https://clear.ml/docs/latest/docs/references/sdk/task/#mark_completed
- https://clear.ml/docs/latest/docs/references/sdk/task/#close

look bad. I do not know how to fix that.

**Comment by pollfly** [comment]
Hi @Make42! Thank you for noticing :) 

1. Use this format for code blocks:
```
<docstring>
<blank_line>
.. code-block:: py   # this is in the same indentation as the rest of the dosctring
<blank_line>
  <code>                # code is indented 2 spaces
  <code>
<blank_line>
<continue_docstring>
```
So it should look like this:
```
        For example, in

        .. code-block:: py

            task.mark_completed()
            from time import sleep
            sleep(30)
            print('This text will not be printed!')

        the text will not be printed, because the Python process is immediately terminated.
```

2. For `Task.close`, I think the issue is the backtick immediately followed by the "d". Write the method, add a space, and then add -ed (or -d since `close` ends with an "e")--that should fix it. 
```
:meth:`close` -ed
```

**Comment by Make42** [comment]
@pollfly : Thanks, I applied what you said in https://github.com/allegroai/clearml/pull/927. This got somewhat messy, because the hyperparameter example pull request was not merged into the clearml repo. Maybe you can merge those.

**Comment by pollfly** [comment]
@Make42 Having both issues in the same PR is fine, just make sure to mention this issue in [allegroai/clearml#927](https://github.com/allegroai/clearml/pull/927)'s description

**Comment by Make42** [comment]
@pollfly : I have. Can you merge https://github.com/allegroai/clearml/pull/927?

**Comment by Make42** [comment]
Has been merged.
